"""phase2_payments_gmail

Revision ID: 9e4e79816de3
Revises: 45e4169519ab
Create Date: 2026-06-17 16:58:50.233013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4e79816de3'
down_revision: Union[str, Sequence[str], None] = '45e4169519ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_razorpay_subscription_id'), 'users', ['razorpay_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_razorpay_subscription_id'), table_name='users')
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'razorpay_subscription_id')
    # ### end Alembic commands ###
